import React from 'react';
import { useLocation } from "react-router-dom";
import jsPDF from "jspdf";
import "jspdf-autotable";
import {
  CCard,
  CCardBody,
  CCardHeader,
  CCol,
  CContainer,
  CRow,
  CButton
} from '@coreui/react';
import {
    cilCloudDownload
  } from "@coreui/icons";
import CIcon from '@coreui/icons-react';

const ViewBooking = () => {
    const location = useLocation();
  const booking = location.state;
  const handleDownloadPDF = () => {
    // Create a new jsPDF instance
    const doc = new jsPDF();


    // Set up the PDF content
   
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.text("This PDF is generated by Spark Bike System 2023", 10, 10);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Booking Details", 10, 30);
doc.addFont("https://fonts.gstatic.com/s/raleway/v14/1Ptpg8zYS_SKggPNwE4ISg.ttf", "Raleway", "normal");

  doc.setFont("Raleway", "normal");
  doc.setFontSize(12);

  // Define the table columns and rows
  const tableColumns = [
    { header: "Field", dataKey: "field" },
    { header: "Value", dataKey: "value" },
  ];

  const tableRows = [
    { field: "Booking ID", value: booking.razorpayOrderId },
    { field: "User ID", value: booking.userId },
    { field: "Bike ID", value: booking.BikeId },
    { field: "Amount", value: `Rs.${booking.amount}` },
    { field: "Pickup Date", value: new Date(booking.pickupDateTime._seconds * 1000).toLocaleString() },
    { field: "Return Date", value: new Date(booking.returnDateTime._seconds * 1000).toLocaleString() },
    { field: "DL No", value: booking.dlNo },
    { field: "Name", value: booking.name },
    { field: "Email", value: booking.email },
    { field: "Brand", value: booking.BikeData.brand },
    { field: "Bike Name", value: booking.BikeData.name },
    { field: "CC", value: booking.BikeData.cc },
    { field: "Passenger", value: booking.BikeData.passanger },
    { field: "Transmission", value: booking.BikeData.transmission },
    { field: "Rate", value: `Rs.${booking.BikeData.rate}` },
  ];

  // Set the table position and style
  const tableOptions = {
    margin: { top: 40 },
    styles: { font: "helvetica", fontSize: 12 },
  };

  // Add the table to the PDF document
  doc.autoTable(tableColumns, tableRows, tableOptions);


    // Download the PDF file
    doc.save(`${booking.razorpayOrderId}.pdf`);
  };
  return (
    <CContainer className="py-4">
      <CRow>
        <CCol>
          <CCard>
            <CCardHeader><h2>Booking Details</h2></CCardHeader>
            <CCardBody>
              <p>Booking ID: {booking.razorpayOrderId}</p>
              <p>User ID: {booking.userId}</p>
              <p>Bike ID: {booking.BikeId}</p>
              <p>Name: {booking.name}</p>
              <p>Email: {booking.email}</p>
              <p>DL Number: {booking.dlNo}</p>
              <p>Amount: {booking.amount}</p>
              <p>Status: {booking.status}</p>
              <p>Pickup Date Time: {new Date(booking.pickupDateTime._seconds * 1000).toLocaleString()}</p>
              <p>Return Date Time: {new Date(booking.returnDateTime._seconds * 1000).toLocaleString()}</p>
              <p>Payment ID: {booking.paymentId}</p>
              <p>Razorpay Order ID: {booking.razorpayOrderId}</p>
              <p>Razorpay Signature: {booking.razorpaySignature}</p>
              <p>Timestamp: {new Date(booking.timestamp._seconds * 1000).toLocaleString()}</p>
              
             
              
            </CCardBody>
          </CCard>
        </CCol>
      </CRow>
      <CRow>
        <CCol>
          <CCard>
            <CCardHeader><h2>Bike Details</h2></CCardHeader>
            <CCardBody>
              
              <p>Bike Name: {booking.BikeData.name}</p>
              <p>Brand: {booking.BikeData.brand}</p>
              <p>CC: {booking.BikeData.cc}</p>
              <p>Transmission: {booking.BikeData.transmission}</p>
              <p>Rate: {booking.BikeData.rate}</p>
              <p>Description: {booking.BikeData.description}</p>
              <p>Passenger: {booking.BikeData.passanger}</p>
              <img
                src={booking.BikeData.img}
                alt={booking.BikeData.name}
                style={{ width: '200px' }}
              />
              <CCol xs={12} className="text-center">
          <CButton type="submit" onClick={handleDownloadPDF}>
          <CIcon icon={cilCloudDownload} style={{ marginRight: '0.5rem' }} />
            Download PDF</CButton>
        </CCol>
            </CCardBody>
          </CCard>
        </CCol>
      </CRow>
    </CContainer>
  );
};

export default ViewBooking;
